//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Locadora
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string cep { get; set; }
        public string bairro { get; set; }
        public string cidade { get; set; }
        public string celular { get; set; }
        public string email { get; set; }
        public System.DateTime dt_inclusao { get; set; }
        public Nullable<System.DateTime> dt_update { get; set; }
        public string status { get; set; }
        public string logradouro { get; set; }
        public Nullable<System.DateTime> dt_nascimento { get; set; }
    }
}
