//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Locadora
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filme
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public string sub_titulo { get; set; }
        public string duracao { get; set; }
        public decimal valor { get; set; }
        public int genero { get; set; }
        public string sinopse { get; set; }
        public Nullable<decimal> nota { get; set; }
        public System.DateTime dt_lancamento { get; set; }
        public int quantidade { get; set; }
        public System.DateTime dt_inclusao { get; set; }
        public Nullable<System.DateTime> dt_update { get; set; }
    
        public virtual Genero Genero1 { get; set; }
    }
}
